# Data Manipulation

In [ ]:
import torch
x = torch.arange(12, dtype=torch.float32)

x
x.numel() #개수 세기
x.shape #tensor의 형태 2차원: (3, 4) = row: 3, col: 4

X = x.reshape(3, 4) #형태 변환 
X

#tensor 생성 : 초기 값 0, 1
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))

#tensor 생성 : 초기 값 가우시안
torch.randn(3, 4) #shape 지정

#tensor 생성 : 초기 값 지정
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

#2차원 tensor Slicing
X[-1], X[1:3]

X[1, 2] = 17 #할당
X

X[:2, :] = 12 #슬라이싱 한 것에 모두 할당
X

#x에 e^x를 값으로 하는 tensor 생성
torch.exp(x)

#각 요소끼리 계산
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

#dim에 따라 가로 또는 세로로 tensor끼리 붙이는 것이 가능
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

#logical 계산도 각 요소끼리 함
X == Y

#broadcasting : 서로 shape이 다른 tensor를 각 요소끼리 계산하기 위해 shape를 자동으로 shape를 맞춰줌
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

a+b #broadcasting 때문에 문제 발생하지 않음

#계산을 할 때 기존에 사용하던 메모리를 다시 사용하기 위한 방법
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

X += Y #계산하기 전 X의 id와 계산 후의 X의 id는 같음

#다른 python 라이브러리와 호환 가능
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

id(Z): 140456830537216
id(Z): 140456830537216


(numpy.ndarray, torch.Tensor)

# Data Preprocessing

In [ ]:
import pandas as pd

#데이터 준비
data_file = "경로"
data = pd.read_csv(data_file)

#특정 데이터를 가져와서 na 값이 들어있는 정보 확인
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)

#na 값 대체 : 전처리
inputs = inputs.fillna(inputs.mean()) #평균으로 대체

#계산을 하기 위한 데이터로 변환하는 과정
import torch

X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

# Linear Algebra

In [ ]:
import torch

#matrix에서 transpose할 수 있음
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A.T

x = torch.arange(3, dtype=torch.float32)
x.sum(), x.mean() #sum을 했을 때 이는 하나의 값이므로 shape이 줄어듬 : reduction
A.mean(axis=0) #axis 로 가로 또는 세로로 평균 연산이 가능

#boradcasting 계산에 대비해 shape이 줄어들지 않도록 할 수 있음
sum_A = A.sum(axis=1, keepdims=True)

#다음 함수를 통해
#dot product, Matrix-Vector Products, Matrix-Matrix Multiplication이 가능함

#dot product
torch.dot(x, y)

#Matrix-Vector Products
torch.mv(A, x), A@x

#Matrix-Matrix Multiplication
torch.mm(A, B), A@B

#norm 
u = torch.tensor([3.0, -4.0])
torch.norm(u) #L2 방식으로 Norm 계산

#vector 만이 아닌 matrix도 지원
torch.norm(torch.ones((4, 9))) #L2 방식으로 Norm 계산

# Automatic Differentiation

In [ ]:
import torch

#gradient를 구하는 기능 제공
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()  #gradient 초기화 
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y = x * x
u = y.detach() #z에 대한 x의 영향만 보기 위해 y를 u로 대체: detach
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])